### ISSUE TITLE
Cannot fine module 'electron-compile'

### ISSUE THREAD

**Issue by raphael10-collab** [thanhlmm/electron-multiple-tabs#1]
After executing `yarn package` I get this error:

![image](https://user-images.githubusercontent.com/70313067/173660475-6282619f-13c8-4556-a5b1-e6b044a501d2.png)

O.S. : Ubuntu 20.04 Desktop

**Comment by thanhlmm** [comment]
Hi @raphael10-collab 

Thanks for reporting. A fix has been pushed, please pull and try again

**Comment by raphael10-collab** [comment]
Hi @thanhlmm !

    (base) raphy@pc:~/electron-multiple-tabs/vite$ yarn build
    yarn run v1.22.18
    warning package.json: No license field
    $ tsc && vite build
    vite v2.3.8 building for production...
    ✓ 86 modules transformed.
    dist/index.html                          1.49kb
    dist/tabs.html                           0.59kb
    dist/assets/main.d85c801e.js             0.94kb
    dist/assets/tabs.a1c4d94b.js             5.09kb
    dist/assets/vendor.abcbfb5d.js           372.95kb
    dist/assets/serviceWorker.f6ef12ff.js    14.21kb
    dist/assets/serviceWorker.11e83971.css   13.00kb
    Done in 5.29s.
    (base) raphy@pc:~/electron-multiple-tabs/vite$ 


On the server side I'm getting `Cannot find module '/home/raphy/electron-multiple-tabs/server/notarize.js'` : 

    (base) raphy@pc:~/electron-multiple-tabs/server$ yarn package
    yarn run v1.22.18
    $ electron-builder
      • electron-builder  version=23.0.3 os=5.13.0-48-generic
      • loaded configuration  file=package.json ("build" field)
      • writing effective config  file=dist/builder-effective-config.yaml
      • packaging       platform=linux arch=x64 electron=12.0.0 appOutDir=dist/linux-unpacked
      • downloading     url=https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip size=79 MB parts=8
      • downloaded      url=https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip duration=6.336s
      • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
      • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
      ⨯ Cannot find module '/home/raphy/electron-multiple-tabs/server/notarize.js'
    Require stack:
    - /home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/out/platformPackager.js
    - /home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/out/electron/ElectronFramework.js
    - /home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/out/packager.js
    - /home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/out/index.js
    - /home/raphy/electron-multiple-tabs/server/node_modules/electron-builder/out/builder.js
    - /home/raphy/electron-multiple-tabs/server/node_modules/electron-builder/out/cli/cli.js
    - /home/raphy/electron-multiple-tabs/server/node_modules/electron-builder/cli.js  failedTask=build stackTrace=Error: Cannot find module '/home/raphy/electron-multiple-tabs/server/notarize.js'
    Require stack:
    - /home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/out/platformPackager.js
    - /home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/out/electron/ElectronFramework.js
    - /home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/out/packager.js
    - /home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/out/index.js
    - /home/raphy/electron-multiple-tabs/server/node_modules/electron-builder/out/builder.js
    - /home/raphy/electron-multiple-tabs/server/node_modules/electron-builder/out/cli/cli.js
    - /home/raphy/electron-multiple-tabs/server/node_modules/electron-builder/cli.js
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
        at Function.Module._load (node:internal/modules/cjs/loader:778:27)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at resolveFunction (/home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/src/platformPackager.ts:766:13)
        at LinuxPackager.doSignAfterPack (/home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/src/platformPackager.ts:330:23)
        at LinuxPackager.doPack (/home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/src/platformPackager.ts:314:7)
        at LinuxPackager.pack (/home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
        at Packager.doBuild (/home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/src/packager.ts:441:9)
        at Object.executeFinally (/home/raphy/electron-multiple-tabs/server/node_modules/builder-util/src/promise.ts:12:14)
        at Packager._build (/home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/src/packager.ts:376:31)
        at Packager.build (/home/raphy/electron-multiple-tabs/server/node_modules/app-builder-lib/src/packager.ts:337:12)
        at Object.executeFinally (/home/raphy/electron-multiple-tabs/server/node_modules/builder-util/src/promise.ts:12:14)
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by thanhlmm** [comment]
Can you pull code and try again? I removed the Notarize file for macos

**Comment by raphael10-collab** [comment]
Now the packaging process seems working fine: 

    (base) raphy@pc:~/electron-multiple-tabs/vite$ yarn build
    yarn run v1.22.18
    warning package.json: No license field
    $ tsc && vite build
    vite v2.3.8 building for production...
    ✓ 86 modules transformed.
    dist/index.html                          1.49kb
    dist/tabs.html                           0.59kb
    dist/assets/main.d85c801e.js             0.94kb
    dist/assets/tabs.a1c4d94b.js             5.09kb
    dist/assets/vendor.abcbfb5d.js           372.95kb
    dist/assets/serviceWorker.f6ef12ff.js    14.21kb
    dist/assets/serviceWorker.11e83971.css   13.00kb

    (base) raphy@pc:~/electron-multiple-tabs/server$ yarn package
    yarn run v1.22.18
    $ electron-builder
      • electron-builder  version=23.0.3 os=5.13.0-48-generic
      • loaded configuration  file=package.json ("build" field)
      • writing effective config  file=dist/builder-effective-config.yaml
      • packaging       platform=linux arch=x64 electron=12.0.0 appOutDir=dist/linux-unpacked
      • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
      • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
      • building        target=deb arch=x64 file=dist/multiple-tab_0.0.1_amd64.deb
      • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
      • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z size=5.0 MB parts=1
      • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z duration=836ms
    Done in 57.98s.

When trying to execute the `.deb` file : 

    (base) raphy@pc:~/electron-multiple-tabs/server/dist$ sudo chmod 777 multiple-tab_0.0.1_amd64.deb
    
    (base) raphy@pc:~/electron-multiple-tabs/server/dist$ ./multiple-tab_0.0.1_amd64.deb
    ./multiple-tab_0.0.1_amd64.deb: line 1: syntax error near unexpected token `newline'
    ./multiple-tab_0.0.1_amd64.deb: line 1: `!<arch>'

**Comment by thanhlmm** [comment]
Nice

**Comment by raphael10-collab** [comment]
On the right path to make it work, but it doesn't work, at the moment:
    
    (base) raphy@pc:~/electron-multiple-tabs/server/dist$ ./multiple-tab_0.0.1_amd64.deb
    ./multiple-tab_0.0.1_amd64.deb: line 1: syntax error near unexpected token `newline'
    ./multiple-tab_0.0.1_amd64.deb: line 1: `!<arch>'

**Comment by thanhlmm** [comment]
Hey I have only macOS env and it works fine. Idk how to solve it in Ubuntu env

**Comment by raphael10-collab** [comment]
By the way,
I'm new to `vite` and I find it interesting, and may be an option to replace `webpack`.

Do you know how to specify in `vite.config.ts` https://github.com/electron-vite/electron-vite-react/blob/main/vite.config.ts different apps each for a different window?

For example:

    /src/app
    /src/app_A 
    /src/app_B

where App.tsx and main.tsx are in /src/app :

    /src/app/App.tsx
    /src/app/main.tsx 
    
    /src/app_A/App_A.tsx
    /src/app_A/main_A.tsx
    
    /src/app_B/App_B.tsx
    /src/app_B/main_B.tsx

**Comment by thanhlmm** [comment]
You can set with `input` like I did
```
input: {
        main: path.resolve(__dirname, "index.html"),
        tabs: path.resolve(__dirname, "tabs.html"),
      },
 ```
 This setting makes the Vite build for 2 entries: index.html and tabs.html

**Comment by raphael10-collab** [comment]
Thank you.

I've found this `Electron-Vite-React` `"template"` https://github.com/electron-vite/electron-vite-react
It could be useful also for you, to make `electron-multiple-tabs` work, after packaged, in `linux` and `window` environments

**Comment by thanhlmm** [comment]
I think you can move the code base for Electron multiple tabs into that template and also contribute back to this repo.
To be honest, I don't have much time to maintain this repo. It would be great if you contribute to it.

**Comment by raphael10-collab** [comment]
At the moment I'm trying to understand how to work with `vite` (I come from `webpack`), but I'm interested to keep `electron-multiple-tabs` "alive", if I understand how to use and deploy `vite` apps...

**Comment by thanhlmm** [comment]
Much appreciate 💪

**Comment by raphael10-collab** [comment]
But I'm still struggling in make two different "apps", each for a different window, working...

Would you be so kind in having a look at it? 

`vite.config.js` :  

```ts
    import { rmSync } from 'fs'
    import { join } from 'path'
    import { defineConfig } from 'vite'
    import react from '@vitejs/plugin-react'
    import electron from 'vite-plugin-electron'
    import renderer from 'vite-plugin-electron/renderer'
    import pkg from './package.json'
    
    rmSync(join(__dirname, 'dist'), { recursive: true, force: true }) // v14.14.0
    
    // https://vitejs.dev/config/
    export default defineConfig({
      resolve: {
        alias: {
          '@': join(__dirname, 'src'),
          'styles': join(__dirname, 'src/assets/styles'),
        },
      },
      plugins: [
        react(),
        electron({
          main: {
            entry: 'electron/main/index.ts',
            vite: {
              build: {
                sourcemap: false,
                outDir: 'dist/electron/main',
              },
            },
          },
          preload: {
            input: {
              // You can configure multiple preload scripts here
              //splash: join(__dirname, 'electron/preload/splash.ts'),
              ipcpreload: join(__dirname, 'electron/preload/ipcpreload.ts'),
            },
            vite: {
              build: {
                // For debug
                sourcemap: 'inline',
                outDir: 'dist/electron/preload',
              }
            },
          },
        }),
        // Enables use of Node.js API in the Renderer-process
        renderer(),
      ],
      build: {
        rollupOptions: {
          input: {
            index: join(__dirname, 'index.html'),           // <-----------------------------------------------------------------------
            index_A: join(__dirname, 'index_A.html'),  // <-----------------------------------------------------------------------
          },
        },
      },
      server: {
        host: pkg.env.VITE_DEV_SERVER_HOST,
        port: pkg.env.VITE_DEV_SERVER_PORT,
      },
})
```

Two `html` files:

```sh

    (base) raphy@pc:~/VitePlayground$ ls -lah
    total 220K
    drwxrwxr-x   9 raphy raphy 4.0K Jun 16 17:37 .
    drwxr-xr-x 106 raphy raphy 4.0K Jun 16 17:17 ..
    drwxrwxr-x   3 raphy raphy 4.0K Jun 16 17:35 dist
    -rw-rw-r--   1 raphy raphy  188 Jun 16 16:03 .editorconfig
    drwxrwxr-x   6 raphy raphy 4.0K Jun 16 17:06 electron
    -rw-rw-r--   1 raphy raphy  816 Jun 16 16:03 electron-builder.json5
    drwxrwxr-x   8 raphy raphy 4.0K Jun 16 17:33 .git
    -rw-rw-r--   1 raphy raphy  472 Jun 16 16:52 index_A.html     // <-----------------------------------------------------------------------
    -rw-rw-r--   1 raphy raphy  471 Jun 16 16:41 index.html          // <-----------------------------------------------------------------------
    -rw-rw-r--   1 raphy raphy 1.1K Jun 16 16:03 LICENSE
    drwxrwxr-x 300 raphy raphy  12K Jun 16 17:35 node_modules
    -rw-rw-r--   1 raphy raphy  877 Jun 16 16:22 package.json
    drwxrwxr-x   2 raphy raphy 4.0K Jun 16 16:03 public
    -rw-rw-r--   1 raphy raphy 3.0K Jun 16 16:03 README.md
    -rw-rw-r--   1 raphy raphy 3.0K Jun 16 16:03 README.zh-CN.md
    drwxrwxr-x   5 raphy raphy 4.0K Jun 16 16:49 src
    -rw-rw-r--   1 raphy raphy  673 Jun 16 16:03 tsconfig.json
    -rw-rw-r--   1 raphy raphy  142 Jun 16 16:03 tsconfig.node.json
    -rw-rw-r--   1 raphy raphy  185 Jun 16 16:03 types.d.ts
    -rw-rw-r--   1 raphy raphy 1.5K Jun 16 17:29 vite.config.ts
    drwxrwxr-x   2 raphy raphy 4.0K Jun 16 16:03 .vscode 
    -rw-rw-r--   1 raphy raphy 128K Jun 16 17:33 yarn.lock
```

`index.html` : 

```html

    <script type="module" src="/src/app/index.tsx"></script>
```

`index_A.html` : 

```html

    <script type="module" src="/src/app_A/index_A.tsx"></script>   // <-----------------------------------------------------------------------
```

`(base) raphy@pc:~/VitePlayground/src/app_A$ nano index_A.tsx` : 
    
```tsx

    import React from 'react'
    import ReactDOM from 'react-dom/client'
    import App_A from './components/App_A'
    import 'styles/index.css'
    
    ReactDOM.createRoot(document.getElementById('root')!).render(
      <React.StrictMode>
        <App_A />
      </React.StrictMode>
    )
```

`src/app_A/components/App_A.tsx` : 

```tsx
    import * as React from 'react'
    
    export default function App_A() {
    
      React.useEffect(() => {
    
    
        return () => { // clean-up function
        }
      }, [])
    
      return (
        <div className='container'>
          <h1 className='heading'>
              App_A welcomes you!
          </h1>
        </div>
      );
    }
```

`/electron/menu/menu.ts` : 

```ts
    import {
      BrowserWindow,
      Menu,
      MenuItem,
      ipcMain,
      app,
      shell,
      dialog,
      MenuItemConstructorOptions
    } from 'electron'
    
    import { join } from 'path'
    
    // 🚧 Use ['ENV_NAME'] to avoid vite:define plugin
    const url = `http://${process.env['VITE_DEV_SERVER_HOST']}:${process.env['VITE_DEV_SERVER_PORT']}`
    
    const ipcpreload = join(__dirname, '../preload/ipcpreload.js')
    
    
    let WindowTypeA: BrowserWindow
    
    async function createWindowTypeA() {
      WindowTypeA = new BrowserWindow({
        title: 'Main window',
        webPreferences: {
          //splash: splash,
          ipcpreload: ipcpreload,
          nodeIntegration: true,
          contextIsolation: true,
          nodeIntegrationInWorker: false,
          nodeIntegrationInSubFrames: false,
          webSecurity: true,
          webviewTag: false,
        },
      })
    
      if (app.isPackaged) {
        WindowTypeA.loadFile(join(__dirname, '../../index_A.html'))   // <--------------------------------------------------------------------------------
      } else {
        WindowTypeA.loadURL(url)
        WindowTypeA.webContents.openDevTools()
      }
    
      // Test active push message to Renderer-process
      WindowTypeA.webContents.on('did-finish-load', () => {
        WindowTypeA?.webContents.send('main-process-message', (new Date).toLocaleString())
      })
    
      // Make all links open with the browser, not with the application
      WindowTypeA.webContents.setWindowOpenHandler(({ url }) => {
        if (url.startsWith('https:')) shell.openExternal(url)
        return { action: 'deny' }
      })
    }
    
    const windowAsubmenu = [
      {
        role: 'OpenWindowA',
        click () {
          createWindowTypeA()
          WindowTypeA.show()
        }
      }
    ]
    
    const template: MenuItemConstructorOptions[] = [
      {
        role: 'fileMenu',
        submenu: [
          {
            role: 'quit'
          }
        ]
      },
    
      {
        label: 'View',
        submenu: [
          {
            label: 'Reload',
            accelerator: 'CmdOrCtrl+R',
            click: (item, focusedWindow) => {
              if (focusedWindow.id === 1){
                BrowserWindow.getAllWindows().forEach(win => {
                  if (win.id > 1) win.close()
                })
              }
              focusedWindow.reload()
            }
          }
        ]
      },
    
      {
        label: 'WindowTypeA',
        submenu: [
          {
            label: 'OpenWindowA',
            click () {
              createWindowTypeA()
              WindowTypeA.show()
            }
          }
        ]
      }
    ]
    
    const menu = Menu.buildFromTemplate(template)
    export default menu
```

`/electron/main/index.ts` :  

```ts
    import { app, BrowserWindow, shell, Menu } from 'electron'
    import { release } from 'os'
    import { join } from 'path'
    
    import menu from '../menu/menu'
    
    // Disable GPU Acceleration for Windows 7
    if (release().startsWith('6.1')) app.disableHardwareAcceleration()
    
    // Set application name for Windows 10+ notifications
    if (process.platform === 'win32') app.setAppUserModelId(app.getName())
    
    if (!app.requestSingleInstanceLock()) {
      app.quit()
      process.exit(0)
    }
    process.env['ELECTRON_DISABLE_SECURITY_WARNINGS'] = 'true'
    
    let mainWindow: BrowserWindow | null = null
    // Here you can add more preload scripts
    const splash = join(__dirname, '../preload/splash.js')
    const ipcpreload = join(__dirname, '../preload/ipcpreload.js')
    
    // 🚧 Use ['ENV_NAME'] to avoid vite:define plugin
    const url = `http://${process.env['VITE_DEV_SERVER_HOST']}:${process.env['VITE_DEV_SERVER_PORT']}`
    
    async function createWindow() {
      mainWindow = new BrowserWindow({
        title: 'Main window',
        webPreferences: {
          //splash: splash,
          ipcpreload: ipcpreload,
          nodeIntegration: true,
          contextIsolation: true,
          nodeIntegrationInWorker: false,
          nodeIntegrationInSubFrames: false,
          webSecurity: true,
          webviewTag: false,
        },
      })
    
      if (app.isPackaged) {
        mainWindow.loadFile(join(__dirname, '../../index.html'))
      } else {
        mainWindow.loadURL(url)
        mainWindow.webContents.openDevTools()
      }
    
      // Test active push message to Renderer-process
      mainWindow.webContents.on('did-finish-load', () => {
        mainWindow?.webContents.send('main-process-message', (new Date).toLocaleString())
      })
    
      // Make all links open with the browser, not with the application
      mainWindow.webContents.setWindowOpenHandler(({ url }) => {
        if (url.startsWith('https:')) shell.openExternal(url)
        return { action: 'deny' }
      })
    }
    
    app.whenReady().then( () => {
      createWindow()
      Menu.setApplicationMenu(menu)
    })
    
    app.on('window-all-closed', () => {
      mainWindow = null
      if (process.platform !== 'darwin') app.quit()
    })
    
    app.on('second-instance', () => {
      if (mainWindow) {
        // Focus on the main window if the user tried to open another
        if (win.isMinimized()) mainWindow.restore()
        mainWindow.focus()
      }
    })
    
    app.on('activate', () => {
      const allWindows = BrowserWindow.getAllWindows()
      if (allWindows.length) {
        allWindows[0].focus()
      } else {
        createWindow()
      }
    })

```

Why when clicking `OpenWindowA`  

![image](https://user-images.githubusercontent.com/70313067/174288421-e17b451b-d224-4c05-b5fc-9fffb8a7792e.png)


it opens the mainWindow again? 

![image](https://user-images.githubusercontent.com/70313067/174288194-18f29142-8254-4378-a8bb-20f8939da78a.png)



Here is the repo: https://github.com/raphael10-collab/VitePlayground.git

What am I missing or / and doing wrongly?

**Comment by thanhlmm** [comment]
```
if (app.isPackaged) {
        WindowTypeA.loadFile(join(__dirname, '../../index_A.html'))   // <--------------------------------------------------------------------------------
      } else {
        WindowTypeA.loadURL(url)
        WindowTypeA.webContents.openDevTools()
      }
```

`WindowTypeA.loadURL(url)` -> should be `WindowTypeA.loadURL(url+'/index_A.html')`

You are in development mode so you need to enter the correct url

**Comment by raphael10-collab** [comment]
Thank you ! That was the problem

**Comment by raphael10-collab** [comment]
@thanhlmm 

I discovered that it works fine in `development mode` but not in "packaged mode":

When commenting the relative part in `vite.config.js` : 

      build: {
        rollupOptions: {
          input: {
            index: join(__dirname, 'index.html'),
            //index_A: join(__dirname, 'index_A.html'),
          },
        },
      },

and in `electron/main/index.ts` : 

    app.whenReady().then( () => {
      createMainWindow()
      //Menu.setApplicationMenu(menu)
    })

both `dev mode` and `packaged mode` work fine: 

    raphy@pc:~/VitePlayground$ yarn run build
    yarn run v1.22.15
    $ tsc && vite build && electron-builder
    (node:21908) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    vite v2.9.12 building for production...
    ✓ 1 modules transformed.
    dist/electron/preload/ipcpreload.js   2.50 KiB / gzip: 0.99 KiB
    dist/electron/preload/ipcpreload.js.map 11.79 KiB
    vite v2.9.12 building for production...
    ✓ 1 modules transformed.
    dist/electron/main/index.js   1.34 KiB / gzip: 0.77 KiB
    vite v2.9.12 building for production...
    ✓ 36 modules transformed.
    dist/index.html           0.61 KiB
    dist/style.9f994278.css   1.46 KiB / gzip: 0.63 KiB
    dist/index.90df7efd.js    140.63 KiB / gzip: 45.34 KiB
      • electron-builder  version=23.0.3 os=5.13.0-51-generic
      • loaded configuration  file=/home/raphy/VitePlayground/electron-builder.json5
      • writing effective config  file=release/2.0.0/builder-effective-config.yaml
      • packaging       platform=linux arch=x64 electron=19.0.4 appOutDir=release/2.0.0/linux-unpacked
      • building        target=AppImage arch=x64 file=release/2.0.0/YourAppName-Linux-2.0.0.AppImage
      • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
    Done in 8.18s.

![image](https://user-images.githubusercontent.com/70313067/174443806-af94a2dc-7be9-407b-910b-051d2842391f.png)

When `index_A` is activated in `vite.config.ts` : 

      build: {
        rollupOptions: {
          input: {
            index: join(__dirname, 'index.html'),
            index_A: join(__dirname, 'index_A.html'),
          },
        },
      },

and the `menu` part is activatedin `/electron/main/index.ts` :  

    app.whenReady().then( () => {
      createMainWindow()
      Menu.setApplicationMenu(menu)
    })

the `development mode` works fine as before : 

    raphy@pc:~/VitePlayground$ yarn dev
    yarn run v1.22.15
    $ vite
    (node:22320) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    
      vite v2.9.12 dev server running at:
    
      > Local: http://127.0.0.1:7777/
    
      ready in 215ms.
    
    vite v2.9.12 building for development...
    
    watching for file changes...
    
    build started...
    vite v2.9.12 building for development...
    
    watching for file changes...
    
    build started...
    ✓ 1 modules transformed.
    transforming (1) electron/main/index.tsdist/electron/preload/ipcpreload.js   4.21 KiB / gzip: 1.21 KiB
    dist/electron/preload/ipcpreload.js.map 12.28 KiB
    built in 92ms.
    ✓ 2 modules transformed.
    dist/electron/main/index.js   3.95 KiB / gzip: 1.25 KiB
    built in 92ms.
    [22373:0618/165407.120600:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
    4:54:07 PM [vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
    32 |              lineNumber: 15,
    33 |              columnNumber: 13
    34 |            }, this)
       |               ^
    35 |          }, void 0, false, {
    36 |            fileName: _jsxFileName,
    
      Plugin: vite:esbuild
      File: /home/raphy/VitePlayground/src/app/components/App.tsx

![image](https://user-images.githubusercontent.com/70313067/174443972-cb70eff1-2c34-41ad-b7a8-9a799bbc4e83.png)


But the `production mode`, the `release` produced with `yarn run build` does not work anymore : 


    raphy@pc:~/VitePlayground$ yarn run build
    yarn run v1.22.15
    $ tsc && vite build && electron-builder
    (node:22549) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    vite v2.9.12 building for production...
    ✓ 1 modules transformed.
    dist/electron/preload/ipcpreload.js   2.50 KiB / gzip: 0.99 KiB
    dist/electron/preload/ipcpreload.js.map 11.79 KiB
    vite v2.9.12 building for production...
    ✓ 2 modules transformed.
    dist/electron/main/index.js   2.40 KiB / gzip: 1.02 KiB
    vite v2.9.12 building for production...
    ✓ 39 modules transformed.
    dist/index_A.html          0.67 KiB
    dist/index.html            0.67 KiB
    dist/index.2ba947a6.js     1.71 KiB / gzip: 0.75 KiB
    dist/index_A.ab7b482d.js   0.33 KiB / gzip: 0.25 KiB
    dist/style.9f994278.css    1.46 KiB / gzip: 0.63 KiB
    dist/index.8bf949c4.js     139.11 KiB / gzip: 44.69 KiB
      • electron-builder  version=23.0.3 os=5.13.0-51-generic
      • loaded configuration  file=/home/raphy/VitePlayground/electron-builder.json5
      • writing effective config  file=release/2.0.0/builder-effective-config.yaml
      • packaging       platform=linux arch=x64 electron=19.0.4 appOutDir=release/2.0.0/linux-unpacked
      • building        target=AppImage arch=x64 file=release/2.0.0/YourAppName-Linux-2.0.0.AppImage
      • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
    Done in 8.11s.
    raphy@pc:~/VitePlayground$ 

    raphy@pc:~/VitePlayground/release/2.0.0$ ./YourAppName-Linux-2.0.0.AppImage 
    [22710:0618/165813.204491:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

![image](https://user-images.githubusercontent.com/70313067/174444150-cb9952b7-00dd-4b7b-8eab-55ad0284e8e9.png)

I tried to modify the path also in `packaged mode` : 

      if (app.isPackaged) {
        //WindowTypeA.loadFile(join(__dirname, '../../index_A.html'))
        WindowTypeA.loadURL(url + '/../../index_A.html')
      } else {
        WindowTypeA.loadURL(url + '/../../index_A.html')
        WindowTypeA.webContents.openDevTools()
  }

But again it does not work 
![image](https://user-images.githubusercontent.com/70313067/174444318-6faaea8e-e524-4da9-82e6-972916acf01f.png)

**Comment by thanhlmm** [comment]
You need to run `yarn run copy-fe`  to copy built files from Vite into Electron, and update the path accordingly to make it works.

When we package an Electron, only its folder get sent to the Build file

**Comment by raphael10-collab** [comment]
Based on what I read here: https://vitejs.dev/guide/build.html#multi-page-app the `build configuration` : 
    
      build: {
        rollupOptions: {
          input: {
            index: join(__dirname, 'index.html'),
            index_A: join(__dirname, 'index_A.html'),
          },
        },
seem ok

I've used this `electron-vite-react` template https://github.com/electron-vite/electron-vite-react/blob/main/package.json#L12
where I do not see `yarn run copy-fe`step during `building` phase.

I had a look at this other `vite template`: https://github.com/cawa-93/vite-electron-builder/blob/main/package.json#L20
to understand how to use thie `yarn run copy-fe` step, but I didn't find it.

Shouldn't be doing everyhing `electron-builder` ? 

The `boilerplate` indicated in the `electron-builder` DOCS : https://www.electron.build/#boilerplates `electron-vite-vue`  , in the `build` phase : https://github.com/electron-vite/electron-vite-vue/blob/main/package.json#L10 uses the same steps: `vite build && electron-builder`

**Comment by thanhlmm** [comment]
"copy-fe": "rm -rf build && cp -r ../vite/dist ./build",

Just a simple command to copy build file from vite to electron folder

**Comment by raphael10-collab** [comment]
Does this `copy-fe` command to copy build file from vite to electron folder has to be done right before `package' command?

    raphy@pc:~/electron-multiple-tabs/server$ yarn package
    yarn run v1.22.15
    $ electron-builder
      • electron-builder  version=23.0.3 os=5.13.0-51-generic
      • loaded configuration  file=package.json ("build" field)
      • writing effective config  file=dist/builder-effective-config.yaml
      • packaging       platform=linux arch=x64 electron=12.0.0 appOutDir=dist/linux-unpacked
      • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
      • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
      • building        target=deb arch=x64 file=dist/multiple-tab_0.0.1_amd64.deb
      • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
    Done in 59.95s.

**Comment by raphael10-collab** [comment]
I do not understand why plain `yarn package` command works fine with `electron-multiple-tabs` , but does not work with just a plain simple app with two empty windows opening...  

    raphy@pc:~/electron-multiple-tabs/server$ yarn package
    yarn run v1.22.15
    $ electron-builder
      • electron-builder  version=23.0.3 os=5.13.0-51-generic
      • loaded configuration  file=package.json ("build" field)
      • writing effective config  file=dist/builder-effective-config.yaml
      • packaging       platform=linux arch=x64 electron=12.0.0 appOutDir=dist/linux-unpacked
      • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
      • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
      • building        target=deb arch=x64 file=dist/multiple-tab_0.0.1_amd64.deb
      • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
    Done in 55.74s.

    raphy@pc:~/electron-multiple-tabs/server/dist/linux-unpacked$ ./multiple-tab 
    15:24:48.331 › checking 1
    15:24:48.345 › found socket 1
    15:24:48.345 › Create background process for refiapp_1
    15:24:48.351 › Done create background process #9322
    15:24:48.450 › Starting IPC server
    15:24:48.453 › [
      '/home/raphy/electron-multiple-tabs/server/dist/linux-unpacked/multiple-tab',
      '/home/raphy/electron-multiple-tabs/server/dist/linux-unpacked/resources/app/server/workers/server.js',
      '--subprocess',
      '0.0.1',
      'refiapp_1'
    ]


How, when and where this `copy-fe` command is used when packaging `electron-multiple-tabs` ? 

https://github.com/thanhlmm/electron-multiple-tabs/blob/main/server/package.json#L16

**Comment by raphael10-collab** [comment]
@thanhlmm commenting `contextIsolation: false`  : 

    const createMainWindow = async () => {
      if (mainWindow) {
        return mainWindow;
      }
      const window = new BrowserWindow({
        show: false,
        width: 1000,
        height: 1000,
        backgroundColor: isMacOS ? "#D1D5DB" : "#6B7280",
        icon: path.join(__dirname, '../assets/icon.icns'),
        titleBarStyle: isMacOS ? 'hiddenInset' : 'default',
        frame: isMacOS,
        webPreferences: {
          devTools: isDev,
          enableRemoteModule: false,
          //contextIsolation: false,
          nodeIntegration: false,
          preload: __dirname + "/tab-preload.js",
          disableDialogs: false,
          safeDialogs: true,
          enableWebSQL: false,
        },
      });

gives this output : no tabs

Why?

![image](https://user-images.githubusercontent.com/70313067/174491794-dc69ccba-c7ad-42ce-bba8-0b6dfd517658.png)
